language: python
python:
  - 3.6
services:
  - docker
install:
  - docker build -t max-breast-cancer-mitosis-detector .
  - docker run -it -d -p 5000:5000 max-breast-cancer-mitosis-detector
before_script:
  - pip install pytest pycurl
script:
  - pytest tests/test.py
